### PR TITLE
Release/0.2.2

### PR DESCRIPTION
**Pull request by klausharbo**
I have been working on further improvements of clojupyter and think it is at a stage where it makes sense to cut a release.  There are quite a few changes to simplify the code to enable easier changes in the future, some additions towards making clojupyter installable using `conda` and supporting Windows.  Highlights from the Changelog:

* Upgrade to nREPL v0.6 - eliminate uncaught stacktrace error
* Address/fix open reported issues
* Eliminate shell script in clojupyter install artifact (call java directly)
* Add clojupyter icons to install, taggable with version number
* Replace shell scripts with lein functions for basic build operation
* Make default kernel install directory clojupyter (instead of clojure)
* Option to install in version-specfic directory
* Updated Docker image
* Introduce handler-based middleware structure similar to nREPL and Ring
* Introduce layered message handling
* Improve code structure, kernel code in `clojupyter.kernel.*`
* Introduce configuration file, loaded at startup, controlling some features
* Extend tests
* Update example notebooks
* Update README.md incl tentative roadmap

See [Changelog](https://github.com/clojupyter/clojupyter/blob/release/0.2.2/Changelog.md) for more details.  

Please take a look and let me know what you think! :-)

The roadmap added to the README (at the end, replacing the TODO) expresses my own interests and intentions for work in the coming couple of months, as I'm thinking that is relevant information for potential users.  I do realise that I do not necessarily get to make calls on this all by myself, but the items listed are things I am willing to commit time to work on.  I don't mind removing it, of course, if that's preferred.  Let me know.

-Klaus.

### CODE REVIEW

**Comment by pdenno** [comment]
On 4/1/19 4:41 AM, Klaus Harbo wrote:
> Please take a look at let me know what you think! :-)

This is great! Thanks! Two minor points:

1) It (release branch) installs as 0.2.2-SNAPSHOT. It also shows up in 
the notebook under the "New" button as that.

2) At least on my Anaconda installation, I start the notebook server 
with jupyter notebook, not jupyter-notebook (as it says in the README).

Best regards,
   Peter

**Comment by klausharbo** [comment]
Re 1) You're right, of course.  I am in fact not sure about proper protocol on this, so I left it unchanged.  I have just updated and pushed a new `project.clj` with the version number "0.2.2".

Re 2) I do too, in fact, use 'jupyter notebook'.  I am not sure *if* there is a difference, or what is the history of the two variants(?).  I believe the README had `jupyter-notebook` and I had no real reason for changing it and so left it as it was.  Easy to change, of course, and happy to do that if we can agree to prefer the two-word variant.

-K.

**Comment by klausharbo** [comment]
It's been a few days since I submitted this PR.  When I submitted [my first PR](https://github.com/clojupyter/clojupyter/pull/79) I got the impression that the customary thing to do for non-trivial changes is to submit a PR for review by other contributors.  However, I'm in doubt what to do in the absence of a response?  Is the default conclusion consent or rejection of the proposed change?

**Comment by klausharbo** [comment]
Reviewing the thread I am realising that I did in fact get a response from @pdenno and that perhaps I should consider that an OK to proceed with the PR?

**Comment by pdenno** [comment]
I thought you had commit access. I used the branch with good results. I 
think you can commit. Anyone else have an opinion here?

**Comment by klausharbo** [comment]
I do have commit access, I'm trying to gauge when it is appropriate to commit to `master`.

**Comment by roryk** [comment]
Heya, thanks for all of the work you've been doing everyone, sorry that I've been radio silent. If @pdenno has been using it and gives the thumbs up, thats good for me. I appreciate being careful about pushing to master and getting feedback when there are a lot of changes, I think that's generally a pretty good idea for projects where folks are actually using the software.

**Comment by klausharbo** [comment]
No worries, just trying to figure out proper protocol around here!  And, yes, it's best to keep regressions as few as possible.  One of the reasons I wanted to tag released revisions is that it makes it easier for users to stick with a version until they choose to upgrade: You simply checkout the release you want and install it.

I will promote `release/0.2.2` to `master`, probably tomorrow.  Thx.

**Comment by roryk** [comment]
Thank you!

**Comment by klausharbo** [comment]
merged

**Pull request merged**
